#!/bin/bash

function missingarg {
	echo missing argument $@
	exit 1
}

[[ -z $1 ]] && missingarg [stanza]
[[ -z $2 ]] && missingarg configuration line to add
[[ -z $3 ]] && missingarg configuration file to tweak

stanza=$1
line=$2
file=$3

mv $file $file.tmp
echo -n $file:[$stanza]...
sed -r "s#^\[$stanza\]#[$stanza]\n$line#" $file.tmp > $file && echo done

